### ISSUE TITLE
SSH Server

### ISSUE THREAD

**Issue by BenHarris** [lurume84/bling-wrt#1]
Hey, great work documenting all of this!

Hit a little snag when enabling dropbear in that my config had multiple spaces between the enable option and value (maybe a markdown formatting thing), so the sed replace didn't work. Just edited the file manually, but some people might not think to check and wonder why it wasn't working!

I also hate vi, so just installed nano...
```
opkg update
opkg install nano
```

As another little update, SFTP wasn't then working for me (using Filezilla). The following solved it for me:
```
opkg update
opkg install openssh-sftp-server
```

**Comment by lurume84** [comment]
Thanks for the update, in the future I will include this sftp server
